export const LOG_IN_REQUESTED = "users.LOG_IN_REQUESTED";
export const LOG_IN_SUCCEEDED = "users.LOG_IN_SUCCEEDED";
export const LOG_IN_FAILED = "users.LOG_IN_FAILED";

export const LOG_OUT_REQUESTED = "users.LOG_OUT_REQUESTED";
export const LOG_OUT_SUCCEEDED = "users.LOG_OUT_SUCCEEDED";
export const LOG_OUT_FAILED = "users.LOG_OUT_FAILED";

export const BACKGROUND_LOG_IN_REQUESTED = "users.BACKGROUND_LOG_IN_REQUESTED";
export const BACKGROUND_LOG_IN_SUCCEEDED = "users.BACKGROUND_LOG_IN_SUCCEEDED";
export const BACKGROUND_LOG_IN_FAILED = "users.BACKGROUND_LOG_IN_FAILED";
