
export const UPDATE_INVENTORY_PRICE_REQUESTED = "products.UPDATE_INVENTORY_PRICE_REQUESTED";
export const UPDATE_INVENTORY_PRICE_SUCCEEDED = "products.UPDATE_INVENTORY_PRICE_SUCCEEDED";
export const UPDATE_INVENTORY_PRICE_FAILED = "products.UPDATE_INVENTORY_PRICE_FAILED";
export const UPDATE_INVENTORY_PRICE_DISCONNECTED = "products.UPDATE_INVENTORY_PRICE_DISCONNECTED";
export const UPDATE_INVENTORY_PRICE_RESET = "products.UPDATE_INVENTORY_PRICE_RESET";
