
export const UPDATE_INVENTORY_PRICE_REQUESTED = "products.UPDATE_INVENTORY_PRICE_REQUESTED";
export const UPDATE_INVENTORY_PRICE_SUCCEEDED = "products.UPDATE_INVENTORY_PRICE_SUCCEEDED";
export const UPDATE_INVENTORY_PRICE_FAILED = "products.UPDATE_INVENTORY_PRICE_FAILED";
export const UPDATE_INVENTORY_PRICE_DISCONNECTED = "products.UPDATE_INVENTORY_PRICE_DISCONNECTED";
export const UPDATE_INVENTORY_PRICE_RESET = "products.UPDATE_INVENTORY_PRICE_RESET";

export const SEARCH_OUTLET_PRODUCTS_REQUESTED = "products.SEARCH_OUTLET_PRODUCTS_REQUESTED";
export const SEARCH_OUTLET_PRODUCTS_SUCCEEDED = "products.SEARCH_OUTLET_PRODUCTS_SUCCEEDED";
export const SEARCH_OUTLET_PRODUCTS_FAILED = "products.SEARCH_OUTLET_PRODUCTS_FAILED";
export const SEARCH_OUTLET_PRODUCTS_DISCONNECTED = "products.SEARCH_OUTLET_PRODUCTS_DISCONNECTED";
export const SEARCH_OUTLET_PRODUCTS_RESET = "products.SEARCH_OUTLET_PRODUCTS_RESET";
