export const base = {
  FONT_SIZE_TINY: 8,
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_EXTRA_LARGE: 24,
  FONT_SIZE_MASSIVE: 34,

  FONT_WEIGHT_LIGHT: "200",
  FONT_WEIGHT_MEDIUM: "500",
  FONT_WEIGHT_BOLD: "700",

  PRIMARY_FONT_FAMILY: "Averta",
  PRIMARY_FONT_FAMILY_BOLD: "Averta-Bold",
  PRIMARY_FONT_FAMILY_SEMI_BOLD: "Averta-Semibold",
  PRIMARY_FONT_FAMILY_THIN: "Averta-Thin",
  PRIMARY_FONT_FAMILY_LIGHT: "Averta-Light",

  SECONDARY_FONT_FAMILY: "SharpSans-Medium",
  SECONDARY_FONT_FAMILY_BOLD: "SharpSans-Bold",
  SECONDARY_FONT_FAMILY_SEMI_BOLD: "SharpSans-Semibold",
  SECONDARY_FONT_FAMILY_THIN: "SharpSans-Thin",
  SECONDARY_FONT_FAMILY_LIGHT: "SharpSans-Light",

  PRIMARY_BACKGROUND_COLOR: "#ffffff",
  PRIMARY_BACKGROUND_COLOR_LIGHT: "#f6f6f6",
  SECONDARY_BACKGROUND_COLOR: "#3d3d3d",
  SECONDARY_BACKGROUND_COLOR_LIGHT: "#d3d3d3",

  PRIMARY_TEXT_BACKGROUND_COLOR: "#ffffff",
  SECONDARY_TEXT_BACKGROUND_COLOR: "#3d3d3d",
  PRIMARY_TEXT_COLOR: "#3d3d3d",
  PRIMARY_TEXT_COLOR_LIGHT: "#d3d3d3",
  SECONDARY_TEXT_COLOR: "#ffffff",
  SECONDARY_TEXT_COLOR_LIGHT: "#ffffff",

  PRIMARY_TEXT_INPUT_BACKGROUND_COLOR: "#ffffff",
  SECONDARY_TEXT_INPUT_BACKGROUND_COLOR: "#3d3d3d",
  PRIMARY_TEXT_INPUT_COLOR: "#3d3d3d",
  SECONDARY_TEXT_INPUT_COLOR: "#ffffff"
};

export const darkTheme = {
  PRIMARY_BACKGROUND_COLOR: "#3d3d3d",
  PRIMARY_BACKGROUND_COLOR_LIGHT: "#797979",

  SECONDARY_BACKGROUND_COLOR: "#ffffff",
  SECONDARY_BACKGROUND_COLOR_LIGHT: "#f7f7f7",

  PRIMARY_TEXT_COLOR: "#ffffff",
  PRIMARY_TEXT_COLOR_LIGHT: "#f7f7f7",
  SECONDARY_TEXT_COLOR: "#3d3d3d",
  PRIMARY_TEXT_BACKGROUND_COLOR: "#3d3d3d",
  SECONDARY_TEXT_BACKGROUND_COLOR: "#ffffff"
};
export const lightTheme = {
  PRIMARY_BACKGROUND_COLOR: "#ffffff",
  PRIMARY_BACKGROUND_COLOR_LIGHT: "#f7f7f7",

  SECONDARY_BACKGROUND_COLOR: "#3d3d3d",
  SECONDARY_BACKGROUND_COLOR_LIGHT: "#797979",
  SECONDARY_BACKGROUND_COLOR_FAINT: "#f2f2f2",

  PRIMARY_TEXT_COLOR: "#3d3d3d",
  PRIMARY_TEXT_COLOR_LIGHT: "#797979",
  SECONDARY_TEXT_COLOR: "#ffffff",
  PRIMARY_TEXT_BACKGROUND_COLOR: "#ffffff",
  SECONDARY_TEXT_BACKGROUND_COLOR: "#3d3d3d"
};

export const colorOptions = {
  orange: {
    PRIMARY_COLOR_FAINT: "#FFF3E0",
    PRIMARY_COLOR_LIGHT: "#FFB74D",
    PRIMARY_COLOR: "#FF9800",
    PRIMARY_COLOR_BOLD: "#EF6C00",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  },
  red: {
    PRIMARY_COLOR_FAINT: "#ff8080",
    PRIMARY_COLOR_LIGHT: "#bd4d4d",
    PRIMARY_COLOR: "#c32727",
    PRIMARY_COLOR_BOLD: "#760000",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  },
  blue: {
    PRIMARY_COLOR_FAINT: "#E3F2FD",
    PRIMARY_COLOR_LIGHT: "#64B5F6",
    PRIMARY_COLOR: "#2196F3",
    PRIMARY_COLOR_BOLD: "#1565C0",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  },
  cyan: {
    PRIMARY_COLOR_FAINT: "#E0F7FA",
    PRIMARY_COLOR_LIGHT: "#4DD0E1",
    PRIMARY_COLOR: "#00BCD4",
    PRIMARY_COLOR_BOLD: "#00838F",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  },
  teal: {
    PRIMARY_COLOR_FAINT: "#E0F2F1",
    PRIMARY_COLOR_LIGHT: "#4DB6AC",
    PRIMARY_COLOR: "#009688",
    PRIMARY_COLOR_BOLD: "#00695C",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  },
  gray: {
    PRIMARY_COLOR_FAINT: "#FAFAFA",
    PRIMARY_COLOR_LIGHT: "#E0E0E0",
    PRIMARY_COLOR: "#9E9E9E",
    PRIMARY_COLOR_BOLD: "#424242",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  },
  purple: {
    PRIMARY_COLOR_FAINT: "#EDE7F6",
    PRIMARY_COLOR_LIGHT: "#9575CD",
    PRIMARY_COLOR: "#673AB7",
    PRIMARY_COLOR_BOLD: "#4527A0",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  },
  green: {
    PRIMARY_COLOR_FAINT: "#E8F5E9",
    PRIMARY_COLOR_LIGHT: "#81C784",
    PRIMARY_COLOR: "#4CAF50",
    PRIMARY_COLOR_BOLD: "#2E7D32",
    PRIMARY_FOREGROUND_COLOR: "#ffffff"
  }
};
export const secondaryColorOptions = {
  orange: {
    SECONDARY_COLOR_FAINT: "#FFF3E0",
    SECONDARY_COLOR_LIGHT: "#FFB74D",
    SECONDARY_COLOR: "#FF9800",
    SECONDARY_COLOR_BOLD: "#EF6C00",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  },
  red: {
    SECONDARY_COLOR_FAINT: "#ff8080",
    SECONDARY_COLOR_LIGHT: "#bd4d4d",
    SECONDARY_COLOR: "#c32727",
    SECONDARY_COLOR_BOLD: "#760000",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  },
  blue: {
    SECONDARY_COLOR_FAINT: "#E3F2FD",
    SECONDARY_COLOR_LIGHT: "#64B5F6",
    SECONDARY_COLOR: "#2196F3",
    SECONDARY_COLOR_BOLD: "#1565C0",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  },
  cyan: {
    SECONDARY_COLOR_FAINT: "#E0F7FA",
    SECONDARY_COLOR_LIGHT: "#4DD0E1",
    SECONDARY_COLOR: "#00BCD4",
    SECONDARY_COLOR_BOLD: "#00838F",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  },
  teal: {
    SECONDARY_COLOR_FAINT: "#E0F2F1",
    SECONDARY_COLOR_LIGHT: "#4DB6AC",
    SECONDARY_COLOR: "#009688",
    SECONDARY_COLOR_BOLD: "#00695C",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  },
  gray: {
    SECONDARY_COLOR_FAINT: "#FAFAFA",
    SECONDARY_COLOR_LIGHT: "#E0E0E0",
    SECONDARY_COLOR: "#9E9E9E",
    SECONDARY_COLOR_BOLD: "#424242",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  },
  purple: {
    SECONDARY_COLOR_FAINT: "#EDE7F6",
    SECONDARY_COLOR_LIGHT: "#9575CD",
    SECONDARY_COLOR: "#673AB7",
    SECONDARY_COLOR_BOLD: "#4527A0",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  },
  green: {
    SECONDARY_COLOR_FAINT: "#E8F5E9",
    SECONDARY_COLOR_LIGHT: "#81C784",
    SECONDARY_COLOR: "#4CAF50",
    SECONDARY_COLOR_BOLD: "#2E7D32",
    SECONDARY_FOREGROUND_COLOR: "#ffffff"
  }
};
