export const FETCH_ORDERS_REQUESTED = "orders.FETCH_ORDERS_REQUESTED";
export const FETCH_ORDERS_SUCCEEDED = "orders.FETCH_ORDERS_SUCCEEDED";
export const FETCH_ORDERS_FAILED = "orders.FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_DISCONNECTED = "orders.FETCH_ORDERS_DISCONNECTED";

export const FETCH_ORDER_DETAILS_REQUESTED = "orders.FETCH_ORDER_DETAILS_REQUESTED";
export const FETCH_ORDER_DETAILS_SUCCEEDED = "orders.FETCH_ORDER_DETAILS_SUCCEEDED";
export const FETCH_ORDER_DETAILS_FAILED = "orders.FETCH_ORDER_DETAILS_FAILED";
export const FETCH_ORDER_DETAILS_DISCONNECTED = "orders.FETCH_ORDER_DETAILS_DISCONNECTED";
