export const FETCH_ORDERS_REQUESTED = "orders.FETCH_ORDERS_REQUESTED";
export const FETCH_ORDERS_SUCCEEDED = "orders.FETCH_ORDERS_SUCCEEDED";
export const FETCH_ORDERS_FAILED = "orders.FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_DISCONNECTED = "orders.FETCH_ORDERS_DISCONNECTED";

export const FETCH_ORDER_DETAILS_REQUESTED = "orders.FETCH_ORDER_DETAILS_REQUESTED";
export const FETCH_ORDER_DETAILS_SUCCEEDED = "orders.FETCH_ORDER_DETAILS_SUCCEEDED";
export const FETCH_ORDER_DETAILS_FAILED = "orders.FETCH_ORDER_DETAILS_FAILED";
export const FETCH_ORDER_DETAILS_DISCONNECTED = "orders.FETCH_ORDER_DETAILS_DISCONNECTED";

export const UPDATE_ORDER_STATUS_REQUESTED = "orders.UPDATE_ORDER_STATUS_REQUESTED";
export const UPDATE_ORDER_STATUS_SUCCEEDED = "orders.UPDATE_ORDER_STATUS_SUCCEEDED";
export const UPDATE_ORDER_STATUS_FAILED = "orders.UPDATE_ORDER_STATUS_FAILED";
export const UPDATE_ORDER_STATUS_DISCONNECTED = "orders.UPDATE_ORDER_STATUS_DISCONNECTED";
export const UPDATE_ORDER_STATUS_RESET = "orders.UPDATE_ORDER_STATUS_RESET";

export const ADD_ORDER_ITEM_REQUESTED = "orders.ADD_ORDER_ITEM_REQUESTED";
export const ADD_ORDER_ITEM_SUCCEEDED = "orders.ADD_ORDER_ITEM_SUCCEEDED";
export const ADD_ORDER_ITEM_FAILED = "orders.ADD_ORDER_ITEM_FAILED";
export const ADD_ORDER_ITEM_DISCONNECTED = "orders.ADD_ORDER_ITEM_DISCONNECTED";
export const ADD_ORDER_ITEM_RESET = "orders.ADD_ORDER_ITEM_RESET";

export const REMOVE_ORDER_ITEM_REQUESTED = "orders.REMOVE_ORDER_ITEM_REQUESTED";
export const REMOVE_ORDER_ITEM_SUCCEEDED = "orders.REMOVE_ORDER_ITEM_SUCCEEDED";
export const REMOVE_ORDER_ITEM_FAILED = "orders.REMOVE_ORDER_ITEM_FAILED";
export const REMOVE_ORDER_ITEM_DISCONNECTED = "orders.REMOVE_ORDER_ITEM_DISCONNECTED";
export const REMOVE_ORDER_ITEM_RESET = "orders.REMOVE_ORDER_ITEM_RESET";

export const SUBSTITUTE_ORDER_ITEM_REQUESTED = "orders.SUBSTITUTE_ORDER_ITEM_REQUESTED";
export const SUBSTITUTE_ORDER_ITEM_SUCCEEDED = "orders.SUBSTITUTE_ORDER_ITEM_SUCCEEDED";
export const SUBSTITUTE_ORDER_ITEM_FAILED = "orders.SUBSTITUTE_ORDER_ITEM_FAILED";
export const SUBSTITUTE_ORDER_ITEM_DISCONNECTED = "orders.SUBSTITUTE_ORDER_ITEM_DISCONNECTED";
export const SUBSTITUTE_ORDER_ITEM_RESET = "orders.SUBSTITUTE_ORDER_ITEM_RESET";


